<script setup>
import {computed,onMounted,ref} from 'vue'
import axios from 'axios'
const API='http://127.0.0.1:8000/api',token=ref(localStorage.getItem('ti_token')||''),user=ref(JSON.parse(localStorage.getItem('ti_user')||'null')),loginData=ref({username:'',password:''}),loginError=ref('')
const api=axios.create({baseURL:API});api.interceptors.request.use(c=>{if(token.value)c.headers.Authorization=`Bearer ${token.value}`;return c})
const appointments=ref([]),users=ref([]),modal=ref(false),userModal=ref(false),passModal=ref(false),editId=ref(null),search=ref(''),status=ref('Todos'),view=ref('lista'),month=ref(new Date()),loading=ref(false),newUser=ref({name:'',username:'',password:'',role:'Técnico'}),pw=ref({current_password:'',new_password:''})
const blank=()=>({title:'',type:'Suporte técnico',requester:'',department:'',location:'',technician:'',date:new Date().toISOString().slice(0,10),startTime:'08:00',endTime:'09:00',priority:'Normal',status:'Agendado',description:'',notes:''}),form=ref(blank())
const isAdmin=computed(()=>user.value?.role==='Administrador'),filtered=computed(()=>appointments.value.filter(a=>{let q=search.value.toLowerCase();return(!q||`${a.ticket_number} ${a.title} ${a.requester} ${a.department} ${a.technician}`.toLowerCase().includes(q))&&(status.value==='Todos'||a.status===status.value)})),today=computed(()=>appointments.value.filter(a=>new Date(a.start).toDateString()===new Date().toDateString()).length),openCount=computed(()=>appointments.value.filter(a=>['Agendado','Em andamento'].includes(a.status)).length),monthLabel=computed(()=>month.value.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})),days=computed(()=>{let y=month.value.getFullYear(),m=month.value.getMonth(),f=new Date(y,m,1),l=new Date(y,m+1,0),a=[];for(let i=0;i<f.getDay();i++)a.push(null);for(let d=1;d<=l.getDate();d++)a.push(new Date(y,m,d));return a})
async function signIn(){loginError.value='';try{let r=await axios.post(API+'/auth/login',loginData.value);token.value=r.data.access_token;user.value=r.data.user;localStorage.setItem('ti_token',token.value);localStorage.setItem('ti_user',JSON.stringify(user.value));await load()}catch(e){loginError.value=e.response?.data?.detail||'Falha no login.'}}
function logout(){token.value='';user.value=null;appointments.value=[];localStorage.removeItem('ti_token');localStorage.removeItem('ti_user')}
async function load(){if(!token.value)return;loading.value=true;try{appointments.value=(await api.get('/appointments')).data;users.value=(await api.get('/users')).data;user.value=(await api.get('/auth/me')).data;localStorage.setItem('ti_user',JSON.stringify(user.value))}catch(e){if(e.response?.status===401)logout();else alert('Erro ao carregar dados.')}finally{loading.value=false}}
function openNew(d=null){editId.value=null;form.value=blank();if(d)form.value.date=d.toISOString().slice(0,10);modal.value=true}
function edit(a){editId.value=a.id;form.value={...a,date:a.start.slice(0,10),startTime:a.start.slice(11,16),endTime:a.end.slice(11,16)};modal.value=true}
async function save(){let p={...form.value,start:`${form.value.date}T${form.value.startTime}:00`,end:`${form.value.date}T${form.value.endTime}:00`};delete p.date;delete p.startTime;delete p.endTime;try{editId.value?await api.put('/appointments/'+editId.value,p):await api.post('/appointments',p);modal.value=false;await load()}catch(e){alert(e.response?.data?.detail||'Erro ao salvar.')}}
async function remove(a){if(confirm(`Excluir ${a.ticket_number}?`)){try{await api.delete('/appointments/'+a.id);await load()}catch(e){alert(e.response?.data?.detail||'Erro ao excluir.')}}}
async function addUser(){try{await api.post('/users',newUser.value);newUser.value={name:'',username:'',password:'',role:'Técnico'};await load()}catch(e){alert(e.response?.data?.detail||'Erro ao cadastrar.')}}
async function deactivate(u){if(confirm(`Desativar ${u.name}?`)){try{await api.patch(`/users/${u.id}/deactivate`);await load()}catch(e){alert(e.response?.data?.detail||'Erro.')}}}
async function changePassword(){try{await api.post('/auth/change-password',pw.value);pw.value={current_password:'',new_password:''};passModal.value=false;alert('Senha alterada.')}catch(e){alert(e.response?.data?.detail||'Erro.')}}
const dayApps=d=>d?appointments.value.filter(a=>new Date(a.start).toDateString()===d.toDateString()):[],icon=t=>t==='Visita técnica'?'👥':t==='Reunião interna'?'🤝':'🛠️',cls=s=>s.toLowerCase().replaceAll(' ','-')
onMounted(load)
</script>
<template><div v-if="!token" class="login"><div class="loginBox"><div class="logo">TI</div><h1>TI Agenda</h1><p>Entre para gerenciar os atendimentos</p><form @submit.prevent="signIn"><label>Usuário<input v-model="loginData.username" required autocomplete="username"></label><label>Senha<input v-model="loginData.password" type="password" required autocomplete="current-password"></label><p class="error" v-if="loginError">{{loginError}}</p><button class="primary wide">Entrar</button></form><small>Primeiro acesso: admin / admin123</small></div></div>
<div v-else class="app"><aside class="sidebar"><div class="brand"><div class="brandIcon">TI</div><div><strong>TI Agenda</strong><small>Gestão de TI</small></div></div><nav><a :class="{active:view==='lista'}" @click="view='lista'">📅 Agenda</a><a @click="view='lista';status='Todos'">🛠️ Chamados</a><a @click="view='cal'">▦ Calendário</a><a v-if="isAdmin" @click="userModal=true">👤 Usuários</a></nav><div class="profile"><b>{{user?.name}}</b><small>{{user?.role}}</small><button @click="passModal=true">Alterar senha</button><button @click="logout">Sair ↗</button></div></aside>
<main class="main"><header><div><h1>Agenda de TI</h1><p>Visitas, reuniões e suporte técnico em um só lugar.</p></div><button class="primary" @click="openNew()">＋ Novo agendamento</button></header><section class="cards"><div class="card"><span>📅</span><div><small>Hoje</small><b>{{today}}</b></div></div><div class="card"><span>🛠️</span><div><small>Em aberto</small><b>{{openCount}}</b></div></div><div class="card"><span>📋</span><div><small>Total</small><b>{{appointments.length}}</b></div></div></section>
<section class="toolbar"><div class="search">🔎 <input v-model="search" placeholder="Pesquisar chamado, pessoa ou setor..."></div><select v-model="status"><option>Todos</option><option>Agendado</option><option>Em andamento</option><option>Concluído</option><option>Cancelado</option></select><button @click="view='lista'" :class="{selected:view==='lista'}">☷ Lista</button><button @click="view='cal'" :class="{selected:view==='cal'}">▦ Mês</button></section>
<section v-if="view==='lista'" class="agenda"><div v-if="loading" class="empty">Carregando...</div><div v-else-if="!filtered.length" class="empty">Nenhum agendamento encontrado.</div><div v-for="a in filtered" :key="a.id" class="appointment"><div class="time"><b>{{new Date(a.start).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}}</b><small>{{new Date(a.start).toLocaleDateString('pt-BR')}}</small></div><div class="line"></div><div class="event"><div class="eventTitle"><span>{{icon(a.type)}}</span><b>{{a.title}}</b><em :class="cls(a.status)">{{a.status}}</em></div><div class="ticket">{{a.ticket_number}} · {{a.type}} · Prioridade {{a.priority}}</div><div class="details"><span>👤 {{a.requester}}</span><span>🏢 {{a.department||'—'}}</span><span>📍 {{a.location||'—'}}</span><span>🧑‍💻 {{a.technician||'—'}}</span></div><p>{{a.description}}</p></div><div class="actions"><button @click="edit(a)">✏️</button><button v-if="isAdmin" @click="remove(a)">🗑️</button></div></div></section>
<section v-else class="calendar"><div class="calHead"><button @click="month=new Date(month.getFullYear(),month.getMonth()-1,1)">‹</button><strong>{{monthLabel}}</strong><button @click="month=new Date(month.getFullYear(),month.getMonth()+1,1)">›</button></div><div class="week"><b v-for="w in ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb']">{{w}}</b></div><div class="days"><div v-for="(d,i) in days" :key="i" class="day" :class="{blank:!d}"><template v-if="d"><div class="dayTop"><b>{{d.getDate()}}</b><button @click="openNew(d)">＋</button></div><div v-for="a in dayApps(d).slice(0,3)" class="mini" @click="edit(a)">{{a.start.slice(11,16)}} · {{a.title}}</div></template></div></div></section>
</main>
<div v-if="modal" class="overlay" @click.self="modal=false"><div class="modal"><div class="modalHead"><h2>{{editId?'Editar agendamento':'Novo agendamento'}}</h2><button @click="modal=false">✕</button></div><form @submit.prevent="save"><div class="grid two"><label>Título*<input v-model="form.title" required></label><label>Tipo<select v-model="form.type"><option>Suporte técnico</option><option>Visita técnica</option><option>Reunião interna</option></select></label></div><div class="grid two"><label>Solicitante*<input v-model="form.requester" required></label><label>Setor / Empresa<input v-model="form.department"></label></div><div class="grid two"><label>Local<input v-model="form.location"></label><label>Técnico<select v-model="form.technician"><option value="">Não definido</option><option v-for="u in users">{{u.name}}</option></select></label></div><div class="grid three"><label>Data<input type="date" v-model="form.date" required></label><label>Início<input type="time" v-model="form.startTime" required></label><label>Fim<input type="time" v-model="form.endTime" required></label></div><div class="grid two"><label>Prioridade<select v-model="form.priority"><option>Baixa</option><option>Normal</option><option>Alta</option><option>Urgente</option></select></label><label>Status<select v-model="form.status"><option>Agendado</option><option>Em andamento</option><option>Concluído</option><option>Cancelado</option></select></label></div><label>Descrição<textarea v-model="form.description"></textarea></label><label>Observações<textarea v-model="form.notes"></textarea></label><div class="modalActions"><button type="button" @click="modal=false">Cancelar</button><button class="primary">Salvar</button></div></form></div></div>
<div v-if="userModal" class="overlay" @click.self="userModal=false"><div class="modal small"><div class="modalHead"><h2>Usuários</h2><button @click="userModal=false">✕</button></div><div v-for="u in users" class="user"><span><b>{{u.name}}</b> · {{u.username}} · {{u.role}}</span><button v-if="u.id!==user.id" @click="deactivate(u)">Desativar</button></div><h3>Novo usuário</h3><form @submit.prevent="addUser"><input v-model="newUser.name" placeholder="Nome completo" required><input v-model="newUser.username" placeholder="Usuário de acesso" required><input v-model="newUser.password" type="password" placeholder="Senha (mínimo 8 caracteres)" minlength="8" required><select v-model="newUser.role"><option>Técnico</option><option>Solicitante</option><option>Administrador</option></select><button class="primary wide">Cadastrar</button></form></div></div>
<div v-if="passModal" class="overlay" @click.self="passModal=false"><div class="modal small"><div class="modalHead"><h2>Alterar senha</h2><button @click="passModal=false">✕</button></div><form @submit.prevent="changePassword"><label>Senha atual<input type="password" v-model="pw.current_password" required></label><label>Nova senha<input type="password" v-model="pw.new_password" minlength="8" required></label><button class="primary wide">Salvar nova senha</button></form></div></div>
</div></template>
