<script setup>
import {computed,onMounted,ref} from 'vue'
import axios from 'axios'
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000/api',token=ref(localStorage.getItem('ti_token')||''),user=ref(JSON.parse(localStorage.getItem('ti_user')||'null')),loginData=ref({username:'',password:''}),loginError=ref('')
const api=axios.create({baseURL:API});api.interceptors.request.use(c=>{if(token.value)c.headers.Authorization=`Bearer ${token.value}`;return c})
const appointments=ref([]),users=ref([]),modal=ref(false),userModal=ref(false),passModal=ref(false),editId=ref(null),search=ref(''),status=ref('Todos'),view=ref('lista'),month=ref(new Date()),loading=ref(false),newUser=ref({name:'',username:'',password:'',role:'Técnico'}),pw=ref({current_password:'',new_password:''})
const blank=()=>({title:'',type:'Suporte técnico',requester:'',department:'',location:'',technician:'',date:new Date().toISOString().slice(0,10),startTime:'08:00',endTime:'09:00',priority:'Normal',status:'Agendado',description:'',notes:''}),form=ref(blank())
const isAdmin=computed(()=>user.value?.role==='Administrador'),filtered=computed(()=>appointments.value.filter(a=>{let q=search.value.toLowerCase();return(!q||`${a.ticket_number} ${a.title} ${a.requester} ${a.department} ${a.technician}`.toLowerCase().includes(q))&&(status.value==='Todos'||a.status===status.value)})),today=computed(()=>appointments.value.filter(a=>new Date(a.start).toDateString()===new Date().toDateString()).length),openCount=computed(()=>appointments.value.filter(a=>['Agendado','Em andamento'].includes(a.status)).length),monthLabel=computed(()=>month.value.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})),days=computed(()=>{let y=month.value.getFullYear(),m=month.value.getMonth(),f=new Date(y,m,1),l=new Date(y,m+1,0),a=[];for(let i=0;i<f.getDay();i++)a.push(null);for(let d=1;d<=l.getDate();d++)a.push(new Date(y,m,d));return a})
async function signIn(){loginError.value='';try{let r=await axios.post(API+'/auth/login',loginData.value);token.value=r.data.access_token;user.value=r.data.user;localStorage.setItem('ti_token',token.value);localStorage.setItem('ti_user',JSON.stringify(user.value));await load()}catch(e){loginError.value=e.response?.data?.detail||'Falha no login.'}}
function logout(){token.value='';user.value=null;appointments.value=[];localStorage.removeItem('ti_token');localStorage.removeItem('ti_user')}
async function load(){if(!token.value)return;loading.value=true;try{appointments.value=(await api.get('/appointments')).data;if(isAdmin.value)users.value=(await api.get('/users')).data}catch(e){if(e.response?.status===401)logout()}finally{loading.value=false}}
async function save(){let p={...form.value,start:form.value.date+'T'+form.value.startTime+':00',end:form.value.date+'T'+form.value.endTime+':00'};try{if(editId.value)await api.put('/appointments/'+editId.value,p);else await api.post('/appointments',p);modal.value=false;await load()}catch(e){alert(e.response?.data?.detail||'Erro ao salvar')}}
function openNew(){editId.value=null;form.value=blank();modal.value=true}
function openEdit(a){editId.value=a.id;let s=new Date(a.start),e=new Date(a.end);form.value={title:a.title,type:a.type,requester:a.requester,department:a.department||'',location:a.location||'',technician:a.technician||'',date:s.toISOString().slice(0,10),startTime:s.toTimeString().slice(0,5),endTime:e.toTimeString().slice(0,5),priority:a.priority,status:a.status,description:a.description||'',notes:a.notes||''};modal.value=true}
async function remove(a){if(!confirm('Excluir '+a.ticket_number+'?'))return;try{await api.delete('/appointments/'+a.id);await load()}catch(e){alert(e.response?.data?.detail||'Erro')}}
async function addUser(){try{await api.post('/users',newUser.value);newUser.value={name:'',username:'',password:'',role:'Técnico'};await load()}catch(e){alert(e.response?.data?.detail||'Erro')}}
async function deactivate(u){if(!confirm('Desativar '+u.name+'?'))return;try{await api.patch('/users/'+u.id+'/deactivate');await load()}catch(e){alert(e.response?.data?.detail||'Erro')}}
async function changePassword(){try{await api.post('/auth/change-password',pw.value);passModal.value=false;pw.value={current_password:'',new_password:''};alert('Senha alterada')}catch(e){alert(e.response?.data?.detail||'Erro')}}
onMounted(load)
</script>
<template>
<div v-if="!user" class="login"><div class="card"><h1>TI Agenda</h1><p>Suporte Técnico</p><form @submit.prevent="signIn"><input v-model="loginData.username" placeholder="Usuário" required autofocus><input v-model="loginData.password" type="password" placeholder="Senha" required><button class="primary wide">Entrar</button><p v-if="loginError" class="error">{{loginError}}</p></form></div></div>
<div v-else class="app"><aside class="sidebar"><div class="brand">TI Agenda</div><nav><button :class="{active:view==='lista'}" @click="view='lista'">Lista</button><button :class="{active:view==='calendario'}" @click="view='calendario'">Calendário</button></nav><div class="stats"><div><b>{{today}}</b><span>Hoje</span></div><div><b>{{openCount}}</b><span>Abertos</span></div></div><div class="userBox"><b>{{user.name}}</b><span>{{user.role}}</span><button @click="passModal=true">Alterar senha</button><button v-if="isAdmin" @click="userModal=true">Usuários</button><button @click="logout">Sair</button></div></aside>
<main><header><h1>{{view==='lista'?'Agendamentos':'Calendário'}}</h1><div class="actions"><input v-model="search" placeholder="Buscar..."><select v-model="status"><option>Todos</option><option>Agendado</option><option>Em andamento</option><option>Concluído</option><option>Cancelado</option></select><button class="primary" @click="openNew">+ Novo</button></div></header>
<div v-if="loading" class="loading">Carregando...</div>
<div v-else-if="view==='lista'" class="list"><div v-for="a in filtered" :key="a.id" class="item" @click="openEdit(a)"><div class="ticket">{{a.ticket_number}}</div><div class="info"><b>{{a.title}}</b><span>{{a.requester}} · {{a.department}} · {{a.technician||'Sem técnico'}}</span></div><div class="meta"><span class="status" :class="a.status">{{a.status}}</span><span>{{new Date(a.start).toLocaleString('pt-BR')}}</span></div><button v-if="isAdmin" class="danger" @click.stop="remove(a)">Excluir</button></div><p v-if="!filtered.length" class="empty">Nenhum agendamento</p></div>
<div v-else class="cal"><div class="calHead"><button @click="month=new Date(month.getFullYear(),month.getMonth()-1,1)">‹</button><h2>{{monthLabel}}</h2><button @click="month=new Date(month.getFullYear(),month.getMonth()+1,1)">›</button></div><div class="grid seven"><div v-for="d in ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb']" class="dow">{{d}}</div><div v-for="(d,i) in days" :key="i" class="day" :class="{empty:!d,today:d&&d.toDateString()===new Date().toDateString()}"><template v-if="d"><span class="num">{{d.getDate()}}</span><div v-for="a in appointments.filter(x=>new Date(x.start).toDateString()===d.toDateString())" :key="a.id" class="event" @click="openEdit(a)">{{a.title}}</div></template></div></div></div>
</main>
<div v-if="modal" class="overlay" @click.self="modal=false"><div class="modal"><div class="modalHead"><h2>{{editId?'Editar':'Novo'}} agendamento</h2><button @click="modal=false">✕</button></div><form @submit.prevent="save"><label>Título<input v-model="form.title" required></label><div class="grid two"><label>Tipo<select v-model="form.type"><option>Suporte técnico</option><option>Manutenção</option><option>Instalação</option><option>Outro</option></select></label><label>Solicitante<input v-model="form.requester" required></label></div><div class="grid two"><label>Departamento<input v-model="form.department"></label><label>Local<input v-model="form.location"></label></div><div class="grid two"><label>Técnico<select v-model="form.technician"><option value="">Não definido</option><option v-for="u in users">{{u.name}}</option></select></label></div><div class="grid three"><label>Data<input type="date" v-model="form.date" required></label><label>Início<input type="time" v-model="form.startTime" required></label><label>Fim<input type="time" v-model="form.endTime" required></label></div><div class="grid two"><label>Prioridade<select v-model="form.priority"><option>Baixa</option><option>Normal</option><option>Alta</option><option>Urgente</option></select></label><label>Status<select v-model="form.status"><option>Agendado</option><option>Em andamento</option><option>Concluído</option><option>Cancelado</option></select></label></div><label>Descrição<textarea v-model="form.description"></textarea></label><label>Observações<textarea v-model="form.notes"></textarea></label><div class="modalActions"><button type="button" @click="modal=false">Cancelar</button><button class="primary">Salvar</button></div></form></div></div>
<div v-if="userModal" class="overlay" @click.self="userModal=false"><div class="modal small"><div class="modalHead"><h2>Usuários</h2><button @click="userModal=false">✕</button></div><div v-for="u in users" class="user"><span><b>{{u.name}}</b> · {{u.username}} · {{u.role}}</span><button v-if="u.id!==user.id" @click="deactivate(u)">Desativar</button></div><h3>Novo usuário</h3><form @submit.prevent="addUser"><input v-model="newUser.name" placeholder="Nome completo" required><input v-model="newUser.username" placeholder="Usuário de acesso" required><input v-model="newUser.password" type="password" placeholder="Senha (mínimo 8 caracteres)" minlength="8" required><select v-model="newUser.role"><option>Técnico</option><option>Solicitante</option><option>Administrador</option></select><button class="primary wide">Cadastrar</button></form></div></div>
<div v-if="passModal" class="overlay" @click.self="passModal=false"><div class="modal small"><div class="modalHead"><h2>Alterar senha</h2><button @click="passModal=false">✕</button></div><form @submit.prevent="changePassword"><label>Senha atual<input type="password" v-model="pw.current_password" required></label><label>Nova senha<input type="password" v-model="pw.new_password" minlength="8" required></label><button class="primary wide">Salvar nova senha</button></form></div></div>
</div></template>
